CREATE TABLE  "STAFF" 
   (	"STAFF_ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40) NOT NULL ENABLE, 
	"ADMIN" VARCHAR2(5) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"F_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"L_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("STAFF_ID", "USERNAME") ENABLE
   );

CREATE TABLE  "SUPPLIERS" 
   (	"SUPPLIER_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(30) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(40) NOT NULL ENABLE, 
	 PRIMARY KEY ("SUPPLIER_NAME") ENABLE
   );

CREATE TABLE  "PRODUCT_CATEGORIES" 
   (	"PRODUCT_CATEGORY" VARCHAR2(40) NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCT_CATEGORY") ENABLE
   );

CREATE TABLE  "PRODUCTS" 
   (	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"SUPPLIER_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"PRODUCT_CATEGORY" VARCHAR2(40) NOT NULL ENABLE, 
	"WHOLESALE_COST" NUMBER NOT NULL ENABLE, 
	"RETAIL_COST" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCT_ID") ENABLE, 
	 UNIQUE ("PRODUCT_NAME") ENABLE, 
	 FOREIGN KEY ("PRODUCT_CATEGORY")
	  REFERENCES  "PRODUCT_CATEGORIES" ("PRODUCT_CATEGORY") ON DELETE CASCADE ENABLE, 
	 FOREIGN KEY ("SUPPLIER_NAME")
	  REFERENCES  "SUPPLIERS" ("SUPPLIER_NAME") ON DELETE CASCADE ENABLE
   );

CREATE TABLE  "ORDER_ORDER_ID" 
   (	"PRODUCT_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"QUANTITY" VARCHAR2(40) NOT NULL ENABLE, 
	"PRICE" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCT_NAME") ENABLE
   );

CREATE TABLE  "ORDERS" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"FNAME" VARCHAR2(40) NOT NULL ENABLE, 
	"LNAME" VARCHAR2(40) NOT NULL ENABLE, 
	"MODES_OF_PAYMENT" VARCHAR2(40) NOT NULL ENABLE, 
	"DATE_OF_ORDER" DATE NOT NULL ENABLE, 
	"DATE_OF_DISPATCH" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID") ENABLE
   );