CREATE SEQUENCE   "SEQ_STAFF"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE   "SEQ_SUPPLIERS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE   "SEQ_PRODUCT_CAT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE   "SEQ_PRODUCTS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE   "SEQ_ORDERS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE   "SEQ_BILL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;

CREATE TABLE  "STAFF" 
   (	"STAFF_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(20) NOT NULL, 
	"PASSWORD" VARCHAR2(40) NOT NULL, 
	"ADMIN" VARCHAR2(5) NOT NULL, 
	"PHONE" VARCHAR2(20) NOT NULL, 
	"F_NAME" VARCHAR2(20) NOT NULL, 
	"L_NAME" VARCHAR2(20) NOT NULL, 
	"EMAIL" VARCHAR2(20) NOT NULL, 
	 PRIMARY KEY ("STAFF_ID", "USERNAME") ENABLE
   );

CREATE TABLE  "SUPPLIERS" 
   (	"SUPPLIER_ID" NUMBER NOT NULL ENABLE, 
	"SUPPLIER_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("SUPPLIER_ID") ENABLE
   );

CREATE TABLE  "PRODUCT_CATAGORIES" 
   (	"CATAGORY_ID" NUMBER NOT NULL ENABLE, 
	"CATAGORY_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("CATAGORY_ID") ENABLE
   );

CREATE TABLE  "PRODUCTS" 
   (	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"STOCK_QUANTITY" NUMBER NOT NULL ENABLE, 
	"RETAIL_COST" NUMBER NOT NULL ENABLE, 
	"WHOLESALE_COST" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCT_ID") ENABLE
   );

CREATE TABLE  "ORDERS" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_F_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"CUSTOMER_L_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"DATE_OF_ORDER" DATE NOT NULL ENABLE, 
	"MODE_OF_PAYMENT" VARCHAR2(10) NOT NULL ENABLE, 
	"DATE_OF_DISPATCH" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID") ENABLE
   );

CREATE TABLE  "PRODUCTS_ORDERED" 
   (	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"COST" NUMBER NOT NULL ENABLE, 
	 FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES  "PRODUCTS" ("PRODUCT_ID") ENABLE, 
	 FOREIGN KEY ("ORDER_ID")
	  REFERENCES  "ORDERS" ("ORDER_ID") ENABLE
   );

CREATE TABLE  "BILL" 
   (	"BIL_NO" NUMBER NOT NULL ENABLE, 
	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"SHIPMENT_COST" NUMBER NOT NULL ENABLE, 
	"TAXES" NUMBER NOT NULL ENABLE, 
	"TOTAL_COST" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("BIL_NO") ENABLE, 
	 FOREIGN KEY ("ORDER_ID")
	  REFERENCES  "ORDERS" ("ORDER_ID") ENABLE
   )